// Copyright © 2026 DevAM. Licensed under the MIT License. See LICENSE in the repository root.

namespace CSharpStyleValidator.Demo;

/// <summary>Incremental generator proving CSharpStyleValidator on netstandard2.0 Roslyn components.</summary>
[Generator]
public sealed class GreetingGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider,
            static (SourceProductionContext productionContext, Compilation compilation) =>
                _EmitGreeting(productionContext, compilation.AssemblyName));
    }

    private static void _EmitGreeting(SourceProductionContext productionContext, string assemblyName)
    {
        string safeName = string.IsNullOrWhiteSpace(assemblyName) ? "World" : assemblyName;
        string source =
            "// <auto-generated/>\n"
            + "namespace CSharpStyleValidator.Demo.Generated;\n"
            + "internal static class Greeting\n"
            + "{\n"
            + "    internal static string Message => \"Hello from "
            + safeName
            + "\";\n"
            + "}\n";
        productionContext.AddSource("Greeting.g.cs", source);
    }
}
